name: Impulsum
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
options:
  bundleIdPrefix: com.adagop
packages:
  netfox:
    url: https://github.com/kasketis/netfox.git
    from: 1.21.0
targets:
  Impulsum:
    type: application
    platform: iOS
    sources: [Impulsum]
    resources: [Resources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.adagop.Impulsum
      INFOPLIST_FILE: Impulsum/Info.plist
    dependencies:
        - package: netfox
schemes:
  Impulsum:
    build:
      targets:
        Impulsum: all
