name: Impulsum
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
options:
  bundleIdPrefix: com.adagop
packages:
  FocusEntity:
    url: https://github.com/rmRizki/FocusEntity
    minorVersion: 1.0.0
  RealityGeometries:
    url: https://github.com/maxxfrazer/RealityGeometries
    minorVersion: 1.1.2
targets:
  Impulsum:
    type: application
    platform: iOS
    sources: [Impulsum]
    resources: [Resources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.adagop.Impulsum
      INFOPLIST_FILE: Impulsum/Info.plist
schemes:
  Impulsum:
    build:
      targets:
        Impulsum: all
