name: Impulsum
settings:
  PRODUCT_NAME: Visi-ble
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
options:
  bundleIdPrefix: com.adagop
packages:
  FocusEntity:
    url: https://github.com/rmRizki/FocusEntity
    minorVersion: 1.0.1
  RealityGeometries:
    url: https://github.com/maxxfrazer/RealityGeometries
    minorVersion: 1.1.2
targets:
  Impulsum:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: [Impulsum]
    resources: [Resources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.adagop.Impulsum
      INFOPLIST_FILE: Impulsum/Info.plist
    preBuildScripts:
      - script: |
          ./Scripts/SwiftLint/swiftlint lint --quiet
        name: Swiftlint
    dependencies:
      - package: FocusEntity
      - package: RealityGeometries

schemes:
  Impulsum:
    build:
      targets:
        Impulsum: all
