name: Impulsum
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
options:
  bundleIdPrefix: com.adagop
targets:
  Impulsum:
    type: application
    platform: iOS
    sources: [Impulsum]
    resources: [Resources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.adagop.Impulsum
      INFOPLIST_FILE: Impulsum/Info.plist
schemes:
  Impulsum:
    build:
      targets:
        Impulsum: all
